### ISSUE TITLE
Support for Complex arrays

### ISSUE THREAD

**Issue by nickkeepfer** [omlins/ParallelStencil.jl#10]
Fantastic module.

Will there be (or is there already, somewhere hidden?) support for complex type arrays. I would love to use this to perform simulations on the Nonlinear Schrodinger Equation (specifically Gross-Pitaevskii), but that isn't possible without this feature. 
![Screenshot from 2021-02-04 18-00-39](https://user-images.githubusercontent.com/45045579/106928001-045a5300-6713-11eb-93c1-6f250c8a3207.png)

**Comment by omlins** [comment]
Thanks for the appreciation @nickkeepfer ! 

That's a very good point: there is no support for complex numbers currently. However, I am very positive that it will require only little work to add support. I will have a look...
