### ISSUE TITLE
finite volume method

### ISSUE THREAD

**Issue by rveltz** [omlins/ParallelStencil.jl#122]
Hi,

This is not an issue. I am wondering if you have an example of use of the finite volume method where the mass is conserved?

Thank you for your help,

Best

**Comment by luraess** [comment]
Hi,
We don't have an example of using ParallelStencil with a Finite Volume methods yet. However, the staggered grid approach used in the mini apps would be conservative if equations are solved in divergent form. If you have any more specific example you are thinking of, fell free to start a thread on Discourse.
Thanks

**Comment by rveltz** [comment]
I was asking this because I was looking at your fantastic lectures https://pde-on-gpu.vaw.ethz.ch/lecture5/#ol_start4_back_to_loops_ii where there is a function `compute_flux!`

**Comment by luraess** [comment]
Ah - I see. We use conservative finite-differences there on a staggered grid which is close to FV and should be pretty conservative.
