### ISSUE TITLE
[JuliaCon/proceedings-review] DOI of paper by Besard et al.

### ISSUE THREAD

**Issue by benegee** [omlins/ParallelStencil.jl#126]
The checklist at https://github.com/JuliaCon/proceedings-review/issues/138 tells me that archival references should have a DOI listed. Here is the DOI of the paper by Besard et al.: https://ieeexplore.ieee.org/document/8471188

**Comment by bgeihe** [comment]
See also https://github.com/JuliaCon/proceedings-review/issues/138#issuecomment-1796282098

**Comment by omlins** [comment]
Thanks, we will update it accordingly.
