### ISSUE TITLE
Include `@tturbo` as loop vectorisation possibility for the CPU backend

### ISSUE THREAD

**Issue by luraess** [omlins/ParallelStencil.jl#33]
Something to consider as alternative or supplement to the current `Threads.@threads` option. The `@tturbo` macro allows for threaded aux instruction exposed by the [LoopVectorization](https://juliasimd.github.io/LoopVectorization.jl/stable/api/#LoopVectorization.@tturbo) package. See here https://github.com/luraess/parallel-gpu-workshop-JuliaCon21#parallel-cpu-implementation for an example.  _There may be some restrictions on handling `if` conditions inside the loop._

**Comment by omlins** [comment]
As long as `@tturbo` cannot handle if statements inside the loops, it is hard to combine it with the approach taken in ParallelStencil to fuse the loops inside a kernel, relying on if-statements. This approach matches very well the approach taken when targeting GPUs and it is essential for many reasons that the approach for CPU and GPU are as similar as possible; and for deciding the overall approach, the GPU performance has clearly priority. 
We definitively need to look again into it when `@tturbo` can handle if statements inside the loops. KernelAbstractions might also give some benefits for CPU performance.

**Comment by omlins** [comment]
reopened as foreseen GPU optimizations should also make the usage of LoopVectorization feasible without or little divergence between CPU and GPU code generation

**Comment by omlins** [comment]
LoopVectorization's future is unsure; instead, code generation for Polyester has been enabled.
