### ISSUE TITLE
GPUCompiler error when running 3D diffusion example on the GPU

### ISSUE THREAD

**Issue by muendlein** [omlins/ParallelStencil.jl#64]
While trying out the provided example, I receive the following error (Julia 1.8):

```
ERROR: MethodError: no method matching return_types(::GPUArrays.var"#5#6", ::Type{Tuple{CUDA.CuKernelContext, CUDA.CuDeviceArray{Float64, 3, 1}, Float64}}, ::GPUCompiler.GPUInterpreter)
Closest candidates are:
  return_types(::Any, ::Any; world, interp) at reflection.jl:1294
  return_types(::Any) at reflection.jl:1294
```

**Comment by luraess** [comment]
Thanks for reporting @muendlein! Could you be more verbose on packages version you used, exact code example you run, etc? That would make it easier to locate the issue.

**Comment by muendlein** [comment]
Using the following package version does work without an error:

  [052768ef] CUDA v3.12.0
⌃ [4d7a3746] ImplicitGlobalGrid v0.11.0
⌅ [da04e1cc] MPI v0.18.2
  [94395366] ParallelStencil v0.6.0
  [91a5bcdd] Plots v1.31.7

**Comment by luraess** [comment]
I was gonna suggest you to try to update the pkgs. Glad it worked!
