### ISSUE TITLE
Please add code for visualization

### ISSUE THREAD

**Issue by Mrc010** [omlins/ParallelStencil.jl#8]
Is it possible to add some code for visualization to [this example](https://github.com/omlins/ParallelStencil.jl#50-lines-example-deployable-on-gpu-and-cpu), as has been described [here](https://github.com/eth-cscs/ImplicitGlobalGrid.jl#straightforward-in-situ-visualization--monitoring)?

**Comment by omlins** [comment]
There is a file in the examples including visualization for the [50-lines-multi-xpu-example](https://github.com/omlins/ParallelStencil.jl#50-lines-multi-xpu-example). You can extract from there what you need to visualize the single-XPU example.

 I added a link to it in the documentation: #9 . Thanks for pointing out that this link was missing.
