### ISSUE TITLE
Caching the GPU kernels?

### ISSUE THREAD

**Issue by korbinian90** [omlins/ParallelStencil.jl#85]
After starting Julia, the first usage / compilation of the GPU kernels takes about 30s for me. This is done everytime when I restart Julia.
Is there a possibility that this is cached?
Since Julia 1.9, it seems to me like most compilation is cached, it would be great, if this is possible for this package as well.

**Comment by omlins** [comment]
@korbinian90 thanks for reporting this issue. However, for caching of compiled code we rely on the packages we use for the backends as CUDA.jl and AMDGPU.jl, and Julia itself of course. Therefore, please open issues regarding compilation caching directly in these packages.
